# Generated by Django 3.1.7 on 2021-03-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210306_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
